version:0.1
phases:
  install:
    commands:
       -aws cloudformation package --template-file lamdaSam.yaml --s3-bucket lamda-pipeline --output-template-file outputLamdaSam.yaml
artifacts:
  type: zip
  files:
      - outputLamdaSam.yaml
      - lamdaSam.yaml
