version: 0.2
phases:
   build:
     commands:
       - echo Build started on `date`
       - mvn compile
   post_build:
     commands:
       - echo Build completed on `date`
       - mvn package -DskipTests
       - aws cloudformation package --template-file lamdaSam.yaml
                                    --s3-bucket lamda-pipeline
                                    --output-template-file outputLamdaSam.yaml
artifacts:
  type: zip
  files:
      - target/dynamodb-0.0.1-SNAPSHOT.jar
      - outputLamdaSam.yaml
      - lamdaSam.yaml
